
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    creationTimestamp: null
    name: wf--e89c4717-clone-build-push
spec:
    params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
    tasks:
        - name: clone-1
          params:
            - name: url
              value: git@github.com:kyle-boxboat/enterprise-app-demo.git
            - name: revision
              value: kyle-test
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: wf--e89c4717-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/customers
            - name: DOCKERFILE
              value: customers/Dockerfile
            - name: CONTEXT
              value: customers
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: wf--e89c4717-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-2
          params:
            - name: url
              value: git@github.com:kyle-boxboat/enterprise-app-demo.git
            - name: revision
              value: kyle-test
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-1
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: wf--e89c4717-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-2
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/orders
            - name: DOCKERFILE
              value: orders/Dockerfile
            - name: CONTEXT
              value: orders
          runAfter:
            - clone-2
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: wf--e89c4717-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-3
          params:
            - name: url
              value: git@github.com:kyle-boxboat/enterprise-app-demo.git
            - name: revision
              value: kyle-test
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-2
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: wf--e89c4717-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-3
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/inventory
            - name: DOCKERFILE
              value: inventory/Dockerfile
            - name: CONTEXT
              value: inventory
          runAfter:
            - clone-3
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: wf--e89c4717-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-4
          params:
            - name: url
              value: git@github.com:kyle-boxboat/enterprise-app-demo.git
            - name: revision
              value: kyle-test
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-3
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: wf--e89c4717-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-4
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/gateway
            - name: DOCKERFILE
              value: gateway/Dockerfile
            - name: CONTEXT
              value: gateway
          runAfter:
            - clone-4
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: wf--e89c4717-shared-data
            - name: dockerconfig
              workspace: registry-credentials
    workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: wf--e89c4717-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-ssh-credentials

...
